spring:
  application:
    name: spring-async
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
  cloud:
    openfeign:
      client:
        config:
          httpClient:
            url: http://google.com
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
            dismiss404: false
            micrometer.enabled: false

  threads:
    virtual:
      enabled: true